-- 코드를 입력하세요
SELECT DATE_FORMAT(OS.SALES_DATE, "%Y-%m-%d") SALES_DATE, OS.PRODUCT_ID, OS.USER_ID, OS.SALES_AMOUNT FROM (
        SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT FROM ONLINE_SALE
        UNION ALL
        SELECT SALES_DATE, PRODUCT_ID, NULL, SALES_AMOUNT FROM OFFLINE_SALE
    ) AS OS
WHERE OS.SALES_DATE LIKE '2022-03%'
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID;