-- 코드를 입력하세요
SELECT ANIMAL_ID, NAME FROM ANIMAL_INS AS INS
    JOIN ANIMAL_OUTS AS OUTS USING (ANIMAL_ID, ANIMAL_TYPE, NAME)
    ORDER BY TIMESTAMPDIFF(DAY, INS.DATETIME, OUTS.DATETIME) DESC
    LIMIT 2