-- 코드를 입력하세요
SELECT CAR_ID, CAR_TYPE, ROUND((DAILY_FEE * (1-DISCOUNT_RATE/100)) * 30,0) AS FEE FROM CAR_RENTAL_COMPANY_CAR AS CAR
    # LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H USING(CAR_ID)
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS D USING(CAR_TYPE)
    WHERE (CAR_TYPE = 'SUV' OR CAR_TYPE = '세단') 
        AND CAR_ID NOT IN (SELECT CAR_ID
                         FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
                         WHERE END_DATE >= '2022-11-1' 
                               AND START_DATE <= '2022-11-30')
        AND DURATION_TYPE = '30일 이상' 
        # AND (ROUND((DAILY_FEE * (100-DISCOUNT_RATE) / 100) * 30,0) >= 500000 && ROUND((DAILY_FEE * (100-DISCOUNT_RATE) / 100) * 30,0) < 2000000)
    GROUP BY CAR_ID
    HAVING FEE >= 500000 AND FEE < 2000000
    ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC