-- 코드를 입력하세요
SELECT YEAR(sales_date) AS YEAR ,MONTH(sales_date) AS MONTH ,COUNT(DISTINCT (U.USER_ID)) AS PUCHASED_USERS, ROUND(COUNT(DISTINCT (U.USER_ID))/(
    SELECT COUNT(DISTINCT USER_ID) FROM USER_INFO
        WHERE joined LIKE '2021-%'
    ),1) AS PUCHASED_RATIO FROM USER_INFO AS U
    JOIN ONLINE_SALE AS ONL ON U.user_id = ONL.user_id
    WHERE U.joined LIKE '2021-%'
    GROUP BY YEAR, MONTH
    ORDER BY YEAR, MONTH
    
    
    
# ROUND(COUNT(DISTINCT (U.USER_ID))/COUNT(U.joined LIKE '2021-%'),1)