-- 코드를 입력하세요
# OUTS.NAME, OUTS.DATETIME
SELECT INS.NAME, INS.DATETIME FROM ANIMAL_OUTS AS OUTS
    RIGHT JOIN ANIMAL_INS AS INS ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
    WHERE OUTS.ANIMAL_ID IS NULL
    ORDER BY INS.DATETIME
    LIMIT 3