-- 코드를 입력하세요
SELECT A.APNT_NO, P.PT_NAME, P.PT_NO, A.MCDP_CD, D.DR_NAME, APNT_YMD AS APNT_YMD FROM APPOINTMENT AS A
    JOIN PATIENT AS P USING (PT_NO)
    JOIN DOCTOR AS D ON (A.MDDR_ID = D.DR_ID)
    WHERE (APNT_CNCL_YN LIKE 'N') AND (A.MCDP_CD LIKE 'CS' AND APNT_YMD LIKE '2022-04-13%')
    ORDER BY APNT_YMD ASC
    