-- 코드를 입력하세요
# SET @HOURS := -1;
# # SELECT HOUR(DATETIME) AS HOUR, COUNT(ANIMAL_ID) AS COUNT FROM ANIMAL_OUTS
# #     GROUP BY HOUR
# #     ORDER BY HOUR
# SELECT @HOURS := @HOURS + 1 AS HOUR, 
#     (
#         SELECT COUNT(*) FROM ANIMAL_OUTS
#         WHERE @HOURS = HOUR(DATETIME)
#     ) AS COUNT FROM ANIMAL_OUTS
# WHERE @HOURS < 23













SET @HOURS := -1;
SELECT @HOURS := @HOURS + 1 AS HOUR,
    (
        SELECT COUNT(*) FROM ANIMAL_OUTS
            WHERE @HOURS = HOUR(DATETIME) 
    ) AS COUNT
FROM ANIMAL_OUTS
    WHERE @HOURS < 23