# # -- 코드를 입력하세요
# SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE, PRODUCT_NAME FROM FOOD_PRODUCT
#     WHERE CATEGORY LIKE '과자' 
#         OR CATEGORY LIKE '국'
#         OR CATEGORY LIKE '김치'
#         OR CATEGORY LIKE '식용유'
#     GROUP BY CATEGORY, PRODUCT_NAME
#     ORDER BY MAX_PRICE DESC

SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME FROM FOOD_PRODUCT
    WHERE (CATEGORY, PRICE) IN (
        SELECT CATEGORY, MAX(PRICE) AS PRICE FROM FOOD_PRODUCT
        WHERE CATEGORY LIKE '과자' 
        OR CATEGORY LIKE '국'
        OR CATEGORY LIKE '김치'
        OR CATEGORY LIKE '식용유'
        GROUP BY CATEGORY
        
    )
    ORDER BY PRICE DESC